### ISSUE TITLE
Create the webpage exactly like the following

### ISSUE THREAD

**Issue by hari2981** [preethia828/task_1-html-css#1]
Website link http://demo.html5xcss3.com/demo.php?cat=html5themes&host=themewagon&temp=HealthCare

you can ignore the action buttons.

**Comment by preethia828** [comment]
Okay

**Comment by preethia828** [comment]
https://github.com/preethia828/task_1-html-css/tree/newbranchname
couldn't Implement the animation on slide effect.

**Comment by hari2981** [comment]
@preethia828  -  looks fine.

There are lot of areas in the developed website which is not same as per the demo site.

_Welcome To Our Health Care Clinic font size_, alignment, the content. Readmore boxess.

Try to replicate the exact site.

**Comment by preethia828** [comment]
ok

**Comment by preethia828** [comment]
https://github.com/preethia828/task_1-html-css/tree/newfile

**Comment by hari2981** [comment]
@preethia828  - Please close this issue.  This looks fine
